# Runs compatibility tests

name: Build Backward Compatibility Mocks

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:

jobs:
  test:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Backward Compatibility Tests
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout tkey repo
        uses: actions/checkout@v3
        with:
          path: ./tkey

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies, bootstrap, pack
        run: |
          cd ./tkey
          npm ci
          npm run pack:lerna

      - name: Clone comp tests
        uses: actions/checkout@master
        with:
          repository: tkey/backward-compatibility-tests
          path: ./backward-compatibility-tests

      - name: Setup comp tests
        run: |
          cd ./backward-compatibility-tests
          npm i
          for filename in ../tkey/packages/* ; do
            echo "installing $filename" || continue
            # ... install packed packages
            packagename="`ls ${filename}| grep tkey`"
            npm i "${filename}/${packagename}"
          done

      - name: Running comp tests
        run: |
          cd ./backward-compatibility-tests
          npm run build-mocks

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Auto
          branch: master
          cwd: "./backward-compatibility-tests"
          message: "Building Mocks from tkey workflow"
          push: true
